"""
===============================================================================
Move Automap OSA Repeat
===============================================================================

Purpose
-------
Automate the characterization of Photonic Integrated Circuits (PICs) by
combining the Suruga fiber positioning platform, the AutoMapper measurement
plan, and the Optical Spectrum Analyzer (OSA).

For each device defined in the measurement plan, the script moves both fiber
arms to the corresponding input/output waveguides, performs an automatic fiber
alignment, acquires the optical spectrum using the OSA, measures the output
power with the power meter, and stores the measurement together with its
metadata.

Workflow
--------
1. Load the chip layout and measurement plan from an Excel file.
2. Connect to the Suruga positioning platform.
3. Connect to the Optical Spectrum Analyzer (OSA).
4. Define or recover the machine origin (WG0).
5. For each measurement:
    • Move both fiber arms to the selected waveguides.
    • Align the left fiber arm.
    • Align the right fiber arm.
    • Acquire an OSA trace.
    • Measure the output optical power.
    • Save the trace and metadata to a text file.
6. Return both fiber arms to the origin position.
7. Close the OSA connection.

Usage
-----
Configure the execution parameters in the configuration section before running
the script.

Important options:

    DEBUG_MODE
        True  -> Interactive execution. The program waits for user
                 confirmation before critical operations, allowing the
                 operator to validate machine movements.

        False -> Fully automatic execution without user interaction.

    USE_SAVED_ORIGIN
        Restore a previously saved machine origin.

    SAVE_ORIGIN
        Save the current machine position as the new origin.

    EXCEL_FILE
        Measurement plan generated by AutoMapper.

Output
------
For each measurement, a text file containing the OSA trace and its associated
metadata is stored under:

    data/<timestamp>/

Requirements
------------
- Suruga positioning platform
- Optical Spectrum Analyzer (Yeni OSA)
- Power Meter
- AutoMapper measurement plan (.xlsx)

===============================================================================
"""

from datetime import datetime
import time
import pic_upv.automaper as automaper
from pic_upv.suruga import System, AxisComponents, Alignment, PowerMeter
import os
import numpy as np
from pic_upv.osa_simple import YeniOSA
# import pic_upv.osa_simple as osa

# ======================================================
# FUNCIONES
# ======================================================

def wait(message="Press Enter to continue...", delay=0):
    """
    Pause execution depending on the execution mode.

    Parameters
    ----------
    message : str
        Message displayed in debug mode.
    delay : float
        Waiting time in seconds when running in automatic mode.

    Examples
    --------
    Wait for user confirmation in interactive mode or continue
    immediately in automatic mode.

    >>> wait("Press Enter to start the OSA...")

    Wait for user confirmation in interactive mode or 5 seconds
    in automatic mode.

    >>> wait("Press Enter to continue...", delay=5)

    Wait 2 seconds only when running in automatic mode.

    >>> wait(delay=2)
    """
    if DEBUG_MODE:
        input(message)
    elif delay > 0:
        time.sleep(delay)


def guardar_origen(x1, x2):

    with open(ORIGIN_FILE, "w") as f:
        f.write(f"{x1}\n")
        f.write(f"{x2}\n")


def cargar_origen():

    with open(ORIGIN_FILE, "r") as f:
        x1 = float(f.readline())
        x2 = float(f.readline())

    return x1, x2

# ======================================================
# Configuración
# ======================================================

DEBUG_MODE = True             # True -> modo debug, False -> modo automático
USE_SAVED_ORIGIN = False      # True -> usar origen guardado
SAVE_ORIGIN = True            # Guardar el origen al iniciar

ORIGIN_FILE = "origin2.txt"

# Archivo Excel que contiene la información del chip y el plan de medición
EXCEL_FILE = "chipMaps/SurugaTest01.xlsx"

# Numero de veces que se repetirá la medición de todos los dispositivos
num_repeticiones = 1

# ======================================================
# Inicialización
# ======================================================
# Definir el nombre de la carpeta donde se almacenaran 
# los archivos de medición del OSA

nameDate = datetime.now().strftime("%Y%m%d_%H%M%S")

#-------------------------------------------------------
# Cargar el chip y el plan de medición desde el archivo 
# Excel
#-------------------------------------------------------

chip, measurement_paths, measurement_plan = automaper.load_chip(
    EXCEL_FILE
)

#-------------------------------------------------------
# Crear el objeto Suruga
#-------------------------------------------------------
suruga = System()
#-------------------------------------------------------
# Crear el objeto Alignment
#-------------------------------------------------------
alignment = Alignment(suruga)
#-------------------------------------------------------
# Crear los objetos AxisComponents para los ejes X1 y X2
#-------------------------------------------------------
x1 = AxisComponents(suruga, "x1")
x2 = AxisComponents(suruga, "x2")

#-------------------------------------------------------
# Definir los parámetros de alineamiento para el brazo
# izquierdo y derecho
#-------------------------------------------------------

flat_left = {
    "main_stage_x": "x1",
    "main_stage_y": "y1",
    "sub_stage_xy": 0,
    "pm_ch": 1,
    "analog_ch": 1,
    "search_range_x": 50,
    "search_range_y": 20,
    "init_range": -30,
}

flat_right = {
    "main_stage_x": "x2",
    "main_stage_y": "y2",
    "sub_stage_xy": 0,
    "pm_ch": 1,
    "analog_ch": 1,
    "search_range_x": 50,
    "search_range_y": 20,
    "init_range": -30,
}

#-------------------------------------------------------
# Concectarse a la plataforma suruga
#------------------------------------------------------
suruga.connect()

#-------------------------------------------------------
# Crear el objeto PowerMeter
#-------------------------------------------------------
pm = PowerMeter(suruga)
channel = 1

#------------------------------------------------------
# Configuración del OSA
#------------------------------------------------------

osa = YeniOSA()
print(osa.connect())

CENTER = 1550
SPAN = 90
RESOLUTION = 0.2
# RESOLUTION = 0.05
SENSITIVITY = -65

osa.setup_sweep(
    center_nm=CENTER,
    span_nm=SPAN,
    resolution_nm=RESOLUTION,
    sensitivity_dbm=SENSITIVITY,
)

# ======================================================
# Logica para definir el punto de origen del sistema, si 
# se va a usar el origen guardado o la posición actual,
# la posicion de inicio siempre deberá ser WG0
# ======================================================

if USE_SAVED_ORIGIN and os.path.exists(ORIGIN_FILE):

    print("Usando origen almacenado...")

    origin_x1, origin_x2 = cargar_origen()

    x1.move_absolute(origin_x1)
    x2.move_absolute(origin_x2)

else:

    print("Usando posición actual como origen...")

    origin_x1 = x1.get_actual_position()
    origin_x2 = x2.get_actual_position()

    if SAVE_ORIGIN:
        guardar_origen(origin_x1, origin_x2)
        
print("Origen de la máquina")
print(f"X1 = {origin_x1:.3f}")
print(f"X2 = {origin_x2:.3f}")

# ======================================================
# Rutina de medicion
# ======================================================

# ------------------------------------------------------
# Repeticiones de la medición
# ------------------------------------------------------

for repeticion in range(num_repeticiones):

    print("\n" + "=" * 50)
    print(f"Repetition {repeticion + 1}/{num_repeticiones}")

    # ------------------------------------------------------
    # Inicio proceso de medición
    # ------------------------------------------------------

    for measurement in measurement_plan:

        x1_relative = -measurement["input"]["x"]

        x2_relative = -measurement["output"]["x"]

        abs_x1 = origin_x1 + x1_relative

        abs_x2 = origin_x2 + x2_relative

        print("\n" + "=" * 50)

        print(f"Device : {measurement['device']}")

        print(
            f"Input  : {measurement['input']['name']}"
        )

        print(
            f"Output : {measurement['output']['name']}"
        )

        print(
            f"Move X1 -> {abs_x1:.3f}"
        )

        print(
            f"Move X2 -> {abs_x2:.3f}"
        )

        #---------------------------------------------------
        # Mover el sistema a la posición absoluta calculada
        #---------------------------------------------------

        x1.move_absolute(abs_x1)
        x2.move_absolute(abs_x2)

        time.sleep(1)

        #---------------------------------------------------
        # Alinear el brazo izquierdo
        #---------------------------------------------------

        print("Aligning left arm ...")

        alignment.set_flat(**flat_left)
        alignment.start_flat()
        alignment.wait_until_complete()    

        time.sleep(1)

        #---------------------------------------------------
        # Alinear el brazo derecho
        #---------------------------------------------------

        print("Aligning right arm ...")

        alignment.set_flat(**flat_right)
        alignment.start_flat()
        alignment.wait_until_complete()    

        time.sleep(1)

        #---------------------------------------------------
        # Medir con el OSA
        #--------------------------------------------------- 
        
        # DEBUG
        wait("Press Enter to start the OSA...")

        osa.run_sweep(
        trace=1,
        averages=1,
        progress_poll_s=0.5,
        start_delay_s=2.0,
        )

        trace = osa.get_trace(
            trace=1,
            metadata_poll_s=0.2,
            metadata_retries=5,
        )

        #---------------------------------------------------
        # Medir la potencia de salida
        #---------------------------------------------------  
        
        medidas = []  

        for i in range(10):
            medidas.append(pm.get_power(channel))
            time.sleep(0.1)

        power = np.mean(medidas)

        time.sleep(1)

        print(f"Potencia: {power:.6f}")  

        #---------------------------------------------------
        # Guardar la informacion en un archivo de texto
        #---------------------------------------------------

        trace.metadata["device"] = measurement['device']
        trace.metadata["input"] = measurement['input']['name']
        trace.metadata["output"] = measurement['output']['name']
        trace.metadata["Power dBm"] = f"{power:.6f}"
        trace.metadata["Repetition"] = f"{repeticion + 1}/{num_repeticiones}"

        filename = (
        f"data/{nameDate}/medicion_{repeticion + 1}_"
        f"{measurement['device']}_"
        f"{measurement['input']['name']}_"
        f"{measurement['output']['name']}.txt"
        )

        trace.save_txt(filename)

        #---------------------------------------------------
        # Solicitar confirmación del usuario para continuar 
        # con la siguiente medición
        #--------------------------------------------------- 
            
        # DEBUG
        wait("Press Enter to continue with next measurement...")

    # ------------------------------------------------------
    # Retornar al origen (WG0) después de completar todas las mediciones
    # ------------------------------------------------------
    print("\n" + "="*40)
    print("Regresando a WG0")
    print(f"Absoluta : ({origin_x1:.3f}, {origin_x2:.3f})")
    print("Relativa : (0.000, 0.000)")

    wait("Press Enter to return to origin...", delay=1)

    x1.move_absolute(origin_x1)
    x2.move_absolute(origin_x2)

# ======================================================
# Rutina de cierre
# ======================================================

osa.close()

print("Measurement routine completed.")